# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc76103bc9fe4c5cc2c87cf08614ca2a09da33ee5d8d43f96b7b3d9b9253985c4b034f7629fec7cfc7a574010615f7dd830f952055c40d92a1487bb62eae24e4

test:
  secret_key_base: 043bee053acff5fe555555c0769ffac418f9379e77ed6d2ae5a395995d70c4d77971505902a132cbfe83c287f1ea3e3c095b8918bedd754c416b423f2e8133ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
